apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
    name: nginx
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
      tier: frontend
  template:
    metadata:
      labels:
        name: nginx
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: mohansai7/nginx:v1